; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool on Tue Oct 30 2018 18:50:03 GMT+0800 (中国标准时间)
G91               ; relative positioning
G1 Z5 F3000 S2    ; lift Z relative to current position
G1 S1 Y-215 F4000 ; move quickly to Y axis endstop and stop there (first pass)
G1 Y5 F4000       ; go back a few mm
G1 S1 Y-215 F3000  ; move slowly to Y axis endstop once more (second pass)
G1 Z-5 F3000 S2   ; lower Z again
G90               ; absolute positioning