; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool on Tue Oct 30 2018 18:50:03 GMT+0800 (中国标准时间)
G91               ; relative positioning
G1 Z5 F3000 S2    ; lift Z relative to current position
G1 S1 X-255 F4000 ; move quickly to X axis endstop and stop there (first pass)
G1 X5 F4000       ; go back a few mm
G1 S1 X-255 F3000  ; move slowly to X axis endstop once more (second pass)
G1 Z-5 F3000 S2   ; lower Z again
G90               ; absolute positioning